apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microshop-prod
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: microshop
  sources:
    - repoURL: https://github.com/pascariucosmin93/magazon.git
      targetRevision: 0.0.78
      path: helm/microshop
      helm:
        valueFiles:
          - $values/environments/prod/values.yaml
    - repoURL: https://github.com/pascariucosmin93/magazon-gitops.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
